name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install dependencies
        run: bundle install
      - name: Run linter
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.6
          - 2.7
          - "3.0"
          - 3.1
          - 3.2
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec

  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      version: ${{ steps.release-please.outputs.version }}
    steps:
      - uses: krystal/release-please-manifest-action@v1
        id: release-please
        with:
          app-id: ${{ vars.RELEASE_PLEASE_GITHUB_APP_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_GITHUB_APP_PRIVATE_KEY }}

  release:
    runs-on: ubuntu-latest
    needs: [lint, test, release-please]
    if: needs.release-please.outputs.release_created
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Export version from tag name
        run: echo "${{ needs.release-please.outputs.version }}" > VERSION
      - name: Build Gem
        run: gem build *.gemspec
      - name: Setup credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{secrets.KRYSTAL_RUBYGEMS_API_KEY}}
      - name: Publish to RubyGems
        run: |
          gem push *.gem
